public with sharing class home {
    string strLength;
    string strBreadth;
    string strFlrTyp;
    string strWallColor;
    
    
    public void lengthSpecification() {
        String strLengthOfSpec;

    }
    public void floorType() {
        String strTypOfWood;
        system.debug('This is my floortype method');

    }
    public void wallColorType() {
        String strWall_1 = 'Green';     //strClr
        system.debug('This is my wallColorType method');

    }
}
