/*public with sharing class MyListExample {
    //Instance of LIST
    List<String> strLst = new List<String>(); // Memory is allocated
    List<String> strLst2;                      //Memory is not allocated yet

    //example-2 add values to list
    List<String> lstOfItems = new List<String>();
    lstOfItems.add('Snack');
    System.debug('@@@:: ' +lstOfItems );
    lstOfItems.add('Chocos');
    System.debug('###::: ' + lstOfItems);
    
}*/

List<String> lstOfItms = new List<String>();
lstOfItms.add('Snacks');
System.debug('@@@:::'+lstOfItms);
lstOfItms.add('Chocos');
System.debug('###:::'+lstOfItms);










