public with sharing class UdemyOne {

    Map<string, List<String>> Apex = new List<String>{Demistifying Apex Collection, Datatypes and veriables in Apex}
    List<String> Lightning = new List<String>{Events in Aura framework, Developing reausable components}
    System.debug('Apex: ' + Apex);
    System.debug('Lightning: ' + Lightning);

    public UdemyOne() {
    }

    List<String> Apex = 

}
